# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:radio-aktywne/template-app-litestar
accountname: radio-aktywne
appname: emistream
description: Emission streaming logic 🔴
docs: true
docsurl: https://radio-aktywne.github.io/app-emistream
email: it@radioaktywne.pl
envprefix: EMISTREAM
events: true
imagename: apps/emistream
importname: emistream
port: 10000
registry: true
releases: true
reponame: app-emistream
repourl: https://github.com/radio-aktywne/app-emistream
sse: true
