services:
  emistream:
    build:
      context: ./
      network: host
    environment:
      - "EMISTREAM__SERVER__HOST=${EMISTREAM__SERVER__HOST:-0.0.0.0}"
      - "EMISTREAM__SERVER__PORTS__HTTP=${EMISTREAM__SERVER__PORTS__HTTP:-10000}"
      - "EMISTREAM__SERVER__PORTS__SRT=${EMISTREAM__SERVER__PORTS__SRT:-10000}"
      - "EMISTREAM__SERVER__TRUSTED=${EMISTREAM__SERVER__TRUSTED:-*}"
      - "EMISTREAM__STREAM__TIMEOUT=${EMISTREAM__STREAM__TIMEOUT:-PT1M}"
      - "EMISTREAM__STREAM__WINDOW=${EMISTREAM__STREAM__WINDOW:-PT1H}"
      - "EMISTREAM__EMIFUSE__SRT__HOST=${EMISTREAM__EMIFUSE__SRT__HOST:-localhost}"
      - "EMISTREAM__EMIFUSE__SRT__PORT=${EMISTREAM__EMIFUSE__SRT__PORT:-9000}"
      - "EMISTREAM__EMIRECORDS__HTTP__SCHEME=${EMISTREAM__EMIRECORDS__HTTP__SCHEME:-http}"
      - "EMISTREAM__EMIRECORDS__HTTP__HOST=${EMISTREAM__EMIRECORDS__HTTP__HOST:-localhost}"
      - "EMISTREAM__EMIRECORDS__HTTP__PORT=${EMISTREAM__EMIRECORDS__HTTP__PORT:-31000}"
      - "EMISTREAM__EMIRECORDS__HTTP__PATH=${EMISTREAM__EMIRECORDS__HTTP__PATH:-}"
      - "EMISTREAM__EMISHOWS__HTTP__SCHEME=${EMISTREAM__EMISHOWS__HTTP__SCHEME:-http}"
      - "EMISTREAM__EMISHOWS__HTTP__HOST=${EMISTREAM__EMISHOWS__HTTP__HOST:-localhost}"
      - "EMISTREAM__EMISHOWS__HTTP__PORT=${EMISTREAM__EMISHOWS__HTTP__PORT:-35000}"
      - "EMISTREAM__EMISHOWS__HTTP__PATH=${EMISTREAM__EMISHOWS__HTTP__PATH:-}"
      - "EMISTREAM__DEBUG=${EMISTREAM__DEBUG:-false}"
    network_mode: host
