---
services:
  emistream:
    build: .
    network_mode: host
    environment:
      - "EMISTREAM_SERVER__HOST=${EMISTREAM_SERVER__HOST:-0.0.0.0}"
      - "EMISTREAM_SERVER__PORT=${EMISTREAM_SERVER__PORT:-10000}"
      - "EMISTREAM_SERVER__CONCURRENCY=${EMISTREAM_SERVER__CONCURRENCY:-}"
      - "EMISTREAM_SERVER__BACKLOG=${EMISTREAM_SERVER__BACKLOG:-2048}"
      - "EMISTREAM_SERVER__KEEPALIVE=${EMISTREAM_SERVER__KEEPALIVE:-5}"
      - "EMISTREAM_STREAM__TIMEOUT=${EMISTREAM_STREAM__TIMEOUT:-60}"
      - "EMISTREAM_STREAM__FORMAT=${EMISTREAM_STREAM__FORMAT:-ogg}"
      - "EMISTREAM_FUSION__HOST=${EMISTREAM_FUSION__HOST:-localhost}"
      - "EMISTREAM_FUSION__PORT=${EMISTREAM_FUSION__PORT:-9000}"
      - "EMISTREAM_EMIRECORDER__HOST=${EMISTREAM_EMIRECORDER__HOST:-localhost}"
      - "EMISTREAM_EMIRECORDER__PORT=${EMISTREAM_EMIRECORDER__PORT:-31000}"
