services:
  emistream:
    build:
      context: ./
      network: host
    environment:
      - "EMISTREAM__SERVER__HOST=${EMISTREAM__SERVER__HOST:-0.0.0.0}"
      - "EMISTREAM__SERVER__PORT=${EMISTREAM__SERVER__PORT:-10000}"
      - "EMISTREAM__STREAM__HOST=${EMISTREAM__STREAM__HOST:-0.0.0.0}"
      - "EMISTREAM__STREAM__PORT=${EMISTREAM__STREAM__PORT:-10000}"
      - "EMISTREAM__STREAM__TIMEOUT=${EMISTREAM__STREAM__TIMEOUT:-PT1M}"
      - "EMISTREAM__STREAM__WINDOW=${EMISTREAM__STREAM__WINDOW:-PT1H}"
      - "EMISTREAM__FUSION__HOST=${EMISTREAM__FUSION__HOST:-localhost}"
      - "EMISTREAM__FUSION__PORT=${EMISTREAM__FUSION__PORT:-9000}"
      - "EMISTREAM__EMIRECORDER__HOST=${EMISTREAM__EMIRECORDER__HOST:-localhost}"
      - "EMISTREAM__EMIRECORDER__PORT=${EMISTREAM__EMIRECORDER__PORT:-31000}"
      - "EMISTREAM__EMISHOWS__HOST=${EMISTREAM__EMISHOWS__HOST:-localhost}"
      - "EMISTREAM__EMISHOWS__PORT=${EMISTREAM__EMISHOWS__PORT:-35000}"
    network_mode: host
