services:
  emistream:
    build:
      context: ./
      network: host
    environment:
      - "EMISTREAM__SERVER__HOST=${EMISTREAM__SERVER__HOST:-0.0.0.0}"
      - "EMISTREAM__SERVER__PORT=${EMISTREAM__SERVER__PORT:-10000}"
      - "EMISTREAM__STREAM__HOST=${EMISTREAM__STREAM__HOST:-0.0.0.0}"
      - "EMISTREAM__STREAM__PORT=${EMISTREAM__STREAM__PORT:-10000}"
      - "EMISTREAM__STREAM__TIMEOUT=${EMISTREAM__STREAM__TIMEOUT:-PT1M}"
      - "EMISTREAM__STREAM__WINDOW=${EMISTREAM__STREAM__WINDOW:-PT1H}"
      - "EMISTREAM__FUSION__SRT__HOST=${EMISTREAM__FUSION__SRT__HOST:-localhost}"
      - "EMISTREAM__FUSION__SRT__PORT=${EMISTREAM__FUSION__SRT__PORT:-9000}"
      - "EMISTREAM__EMIRECORDER__HTTP__SCHEME=${EMISTREAM__EMIRECORDER__HTTP__SCHEME:-http}"
      - "EMISTREAM__EMIRECORDER__HTTP__HOST=${EMISTREAM__EMIRECORDER__HTTP__HOST:-localhost}"
      - "EMISTREAM__EMIRECORDER__HTTP__PORT=${EMISTREAM__EMIRECORDER__HTTP__PORT:-31000}"
      - "EMISTREAM__EMIRECORDER__HTTP__PATH=${EMISTREAM__EMIRECORDER__HTTP__PATH:-}"
      - "EMISTREAM__EMIRECORDER__SRT__HOST=${EMISTREAM__EMIRECORDER__SRT__HOST:-localhost}"
      - "EMISTREAM__EMIRECORDER__SRT__PORT=${EMISTREAM__EMIRECORDER__SRT__PORT:-31000}"
      - "EMISTREAM__EMISHOWS__HTTP__SCHEME=${EMISTREAM__EMISHOWS__HTTP__SCHEME:-http}"
      - "EMISTREAM__EMISHOWS__HTTP__HOST=${EMISTREAM__EMISHOWS__HTTP__HOST:-localhost}"
      - "EMISTREAM__EMISHOWS__HTTP__PORT=${EMISTREAM__EMISHOWS__HTTP__PORT:-35000}"
      - "EMISTREAM__EMISHOWS__HTTP__PATH=${EMISTREAM__EMISHOWS__HTTP__PATH:-}"
    network_mode: host
