services:
  emistream:
    build:
      context: ./
      network: host
    network_mode: host
    environment:
      - "EMISTREAM__SERVER__HOST=${EMISTREAM__SERVER__HOST:-0.0.0.0}"
      - "EMISTREAM__SERVER__PORT=${EMISTREAM__SERVER__PORT:-10000}"
      - "EMISTREAM__STREAM__TIMEOUT=${EMISTREAM__STREAM__TIMEOUT:-60}"
      - "EMISTREAM__STREAM__FORMAT=${EMISTREAM__STREAM__FORMAT:-ogg}"
      - "EMISTREAM__FUSION__HOST=${EMISTREAM__FUSION__HOST:-localhost}"
      - "EMISTREAM__FUSION__PORT=${EMISTREAM__FUSION__PORT:-9000}"
      - "EMISTREAM__EMIRECORDER__HOST=${EMISTREAM__EMIRECORDER__HOST:-localhost}"
      - "EMISTREAM__EMIRECORDER__PORT=${EMISTREAM__EMIRECORDER__PORT:-31000}"
