[tool.poetry]
name = "emistream"
version = "0.6.0"
description = "Emission streaming logic 🔴"
authors = ["radio-aktywne <it@radioaktywne.pl>"]

[tool.poetry.dependencies]
python = "^3.11"
# Pydantic is used to define data models
pydantic = { version = "^1.10", extras = ["dotenv"] }
# OmegaConf is used to load configuration
omegaconf = "^2.3"
# Typer and Rich are used to build CLIs
typer = { version = "^0.9", extras = ["all"] }
rich = "^13.4"
# Litestar and Uvicorn are used to build async APIs
litestar = "^2.0.0b1"
uvicorn = { version = "^0.22", extras = ["standard"] }
# pyhumps is used to convert between different case styles
pyhumps = "^3.8"
# Streaming utilities
pystreams = { git = "https://github.com/radio-aktywne/package-pystreams.git", tag = "0.3.2" }
# For correct handling of timezones
tzdata = "*"
# Helps building API clients
gracy = "^1.27"

[tool.poetry.group.test.dependencies]
pytest = "^7"
pytest-asyncio = "^0.21"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.poetry.scripts]
# Register CLI
emistream = "emistream.__main__:cli"

# See: https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
